export const MESSAGE = Object.freeze({
  guide: '안녕하세요! 우테코 식당 12월 이벤트 플래너입니다.',
  date: '12월 중 식당 예상 방문 날짜는 언제인가요? (숫자만 입력해 주세요!)\n',
  menu: '주문하실 메뉴를 메뉴와 개수를 알려 주세요. (e.g. 해산물파스타-2,레드와인-1,초코케이크-1)\n',
  order: '<주문 메뉴>',
  amount: '\n<할인 전 총주문 금액>',
  service: '\n<증정 메뉴>',
  benefit: '\n<혜택 내역>',
  benefitAmount: '\n<총혜택 금액>',
  totalAmount: '\n<할인 후 예상 결제 금액>',
  serviceEvent: '증정 이벤트: -25,000원',
  none: '없음',
  badge: '\n<12월 이벤트 배지>',
  badgeSanta: '산타',
  badgeTree: '트리',
  badgeStar: '별',
});
